# Site settings
title: Ted Pettersson Portfolio
email: ted.pettersson@onlinegroup.com
description: > # this means to ignore newlines until "baseurl:"
  Välkommen till min nya hemsida, här kommer det presenteras tankar och material och 
  experiment jag pysslar med både professionellt men även privat. Trevlig läsning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tedpettersson86
github_username:  tedpettersson86

# Build settings
markdown: kramdown
